import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Kimberly Wilkes Portfolio",
  description:
    "Generated by create next app, a portfolio created for Boston University's CS 601",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <Link className="link" href="/">
            <h1>Kimberly Wilkes</h1>
          </Link>
          <nav>
            <Link className="link" href="/about-me">
              About Me
            </Link>
            <Link className="link" href="/work-experience">
              Work Experience
            </Link>
            <Link className="link" href="/village-values">
              Village Values
            </Link>
          </nav>
        </header>
        <main>{children}</main>
        <footer>
          <a
            className="link icon-link"
            href="https://www.linkedin.com/in/kimberly-wilkes/"
            target="_blank"
            rel="noopener noreferrer"
          >
            <Image src="/globe.svg" alt="File icon" width={16} height={16} />
            LinkedIn
          </a>
          <a
            className="link icon-link"
            href="https://github.com/kimdolion"
            target="_blank"
            rel="noopener noreferrer"
          >
            <Image
              aria-hidden
              src="/window.svg"
              alt="Window icon"
              width={16}
              height={16}
            />
            Github
          </a>
          <a
            className="link icon-link"
            href="https://www.villagevalues.org/"
            target="_blank"
            rel="noopener noreferrer"
          >
            <Image
              aria-hidden
              src="/globe.svg"
              alt="Globe icon"
              width={16}
              height={16}
            />
            Village Values
          </a>
        </footer>
      </body>
    </html>
  );
}
